import "server-only";
import ExcelJS from "exceljs";
import { toMajorUnits } from "@/lib/money";
import { REPORT_APP_NAME, type ReportDefinition } from "@/lib/report";

const HEADER_FILL = "FF1E293B";
const ACCENT_FILL = "FFF1F5F9";

/**
 * Renders a report definition to an .xlsx buffer: a titled metadata block,
 * a frozen styled header row, typed cells (so Excel can sum and sort), and a
 * totals row for numeric columns.
 */
export async function buildExcelReport<T>(report: ReportDefinition<T>): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = REPORT_APP_NAME;
  workbook.created = report.generatedAt;

  const sheet = workbook.addWorksheet(report.title.slice(0, 30) || "Report", {
    views: [{ state: "frozen", ySplit: 0 }],
  });

  const columnCount = report.columns.length;

  const addMetaRow = (label: string, value: string) => {
    const row = sheet.addRow([label, value]);
    row.getCell(1).font = { bold: true, size: 10, color: { argb: "FF475569" } };
    row.getCell(2).font = { size: 10 };
    return row;
  };

  const titleRow = sheet.addRow([REPORT_APP_NAME]);
  titleRow.getCell(1).font = { bold: true, size: 16 };
  sheet.mergeCells(titleRow.number, 1, titleRow.number, Math.max(2, columnCount));

  const subtitleRow = sheet.addRow([report.title]);
  subtitleRow.getCell(1).font = { bold: true, size: 12, color: { argb: "FF334155" } };
  sheet.mergeCells(subtitleRow.number, 1, subtitleRow.number, Math.max(2, columnCount));

  if (report.subtitle) {
    const row = sheet.addRow([report.subtitle]);
    row.getCell(1).font = { size: 10, color: { argb: "FF64748B" } };
    sheet.mergeCells(row.number, 1, row.number, Math.max(2, columnCount));
  }

  sheet.addRow([]);
  addMetaRow("Generated at", report.generatedAt.toLocaleString("en-GB"));
  addMetaRow("Generated by", report.generatedBy);
  addMetaRow("Total records", String(report.rows.length));

  sheet.addRow([]);
  const filtersHeading = sheet.addRow(["Applied filters"]);
  filtersHeading.getCell(1).font = { bold: true, size: 11 };
  for (const filter of report.filters) addMetaRow(filter.label, filter.value);

  if (report.summary.length > 0) {
    sheet.addRow([]);
    const summaryHeading = sheet.addRow(["Summary"]);
    summaryHeading.getCell(1).font = { bold: true, size: 11 };
    for (const item of report.summary) addMetaRow(item.label, item.value);
  }

  sheet.addRow([]);

  const headerRow = sheet.addRow(report.columns.map((column) => column.header));
  headerRow.eachCell((cell) => {
    cell.font = { bold: true, color: { argb: "FFFFFFFF" }, size: 11 };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: HEADER_FILL } };
    cell.alignment = { vertical: "middle", horizontal: "left" };
    cell.border = { bottom: { style: "thin", color: { argb: "FF94A3B8" } } };
  });
  headerRow.height = 22;

  // Everything above the header is metadata; freezing here keeps the column
  // titles visible while scrolling the data.
  sheet.views = [{ state: "frozen", ySplit: headerRow.number }];

  const firstDataRow = headerRow.number + 1;

  for (const [index, item] of report.rows.entries()) {
    const values = report.columns.map((column) => {
      const raw = column.value(item);
      if (raw === null || raw === undefined) return "";
      if (column.format === "currency" && typeof raw === "number") {
        return toMajorUnits(raw);
      }
      return raw;
    });

    const row = sheet.addRow(values);
    if (index % 2 === 1) {
      row.eachCell((cell) => {
        cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: ACCENT_FILL } };
      });
    }

    report.columns.forEach((column, columnIndex) => {
      const cell = row.getCell(columnIndex + 1);
      switch (column.format) {
        case "currency":
          cell.numFmt = '#,##0.00;[Red]-#,##0.00';
          cell.alignment = { horizontal: "right" };
          break;
        case "number":
          cell.numFmt = "#,##0";
          cell.alignment = { horizontal: "right" };
          break;
        case "date":
          cell.numFmt = "dd mmm yyyy";
          break;
        case "datetime":
          cell.numFmt = "dd mmm yyyy hh:mm";
          break;
        default:
          cell.alignment = { vertical: "top", wrapText: true };
      }
    });
  }

  const lastDataRow = sheet.lastRow?.number ?? firstDataRow;

  if (report.totalColumns?.length && report.rows.length > 0) {
    const totalsRow = sheet.addRow(
      report.columns.map((_, index) =>
        index === 0
          ? "Total"
          : report.totalColumns?.includes(index)
            ? {
                formula: `SUM(${sheet.getColumn(index + 1).letter}${firstDataRow}:${sheet.getColumn(index + 1).letter}${lastDataRow})`,
              }
            : "",
      ),
    );
    totalsRow.eachCell((cell, colNumber) => {
      cell.font = { bold: true };
      cell.border = { top: { style: "double", color: { argb: "FF334155" } } };
      if (report.totalColumns?.includes(colNumber - 1)) {
        cell.numFmt = '#,##0.00';
        cell.alignment = { horizontal: "right" };
      }
    });
  }

  report.columns.forEach((column, index) => {
    sheet.getColumn(index + 1).width = column.width ?? 20;
  });

  if (report.rows.length > 0) {
    sheet.autoFilter = {
      from: { row: headerRow.number, column: 1 },
      to: { row: lastDataRow, column: columnCount },
    };
  }

  const arrayBuffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(arrayBuffer);
}
